class_name MapDef
extends RefCounted
## "Toy Kingdom Crossroads": castle in the center, 4 winding lanes (N, E, S, W) generated by
## rotating one template path by 90 degrees, so every player's lane is equally hard.
## Ground plane coordinates are Vector2(x, z).

const CASTLE_R := 4.6
const HORN_R := 6.5          # F within this distance of the castle center calls the next wave
const BOUND := 40.0
const ROAD_W := 2.6
const SPOT_R := 1.25

## north lane template: from spawn (far -z) to the castle gate
const TEMPLATE := [
	Vector2(0, -37), Vector2(-7, -32), Vector2(-7, -24), Vector2(6, -19.5),
	Vector2(6, -11.5), Vector2(0, -6.2),
]
const SPOT_FRACTIONS := [0.16, 0.3, 0.44, 0.58, 0.72, 0.86]

var lanes: Array = []        # Array[PackedVector2Array]
var lane_len: Array = []     # Array[PackedFloat32Array] cumulative
var spots: Array = []        # Array of {id, lane, pos: Vector2}

func _init() -> void:
	for k in 4:
		var pts := PackedVector2Array()
		for p in TEMPLATE:
			pts.append(rot(p, k))
		lanes.append(pts)
		var cum := PackedFloat32Array([0.0])
		for i in range(1, pts.size()):
			cum.append(cum[i - 1] + pts[i].distance_to(pts[i - 1]))
		lane_len.append(cum)
	var sid := 0
	for k in 4:
		var side := 1.0
		for f in SPOT_FRACTIONS:
			var d: float = f * length(k)
			var p := pos_at(k, d)
			var t := dir_at(k, d)
			var n := Vector2(-t.y, t.x)
			var cand := p + n * side * 3.0
			if dist_to_any_road(cand) < 2.5:
				cand = p - n * side * 3.0
			spots.append({"id": sid, "lane": k, "pos": cand})
			sid += 1
			side = -side

static func rot(p: Vector2, k: int) -> Vector2:
	var v := p
	for i in k:
		v = Vector2(-v.y, v.x)
	return v

func length(lane: int) -> float:
	var c: PackedFloat32Array = lane_len[lane]
	return c[c.size() - 1]

func pos_at(lane: int, d: float) -> Vector2:
	var pts: PackedVector2Array = lanes[lane]
	var c: PackedFloat32Array = lane_len[lane]
	d = clampf(d, 0.0, c[c.size() - 1])
	for i in range(1, pts.size()):
		if d <= c[i]:
			var seg := c[i] - c[i - 1]
			var k := (d - c[i - 1]) / maxf(seg, 0.0001)
			return pts[i - 1].lerp(pts[i], k)
	return pts[pts.size() - 1]

func dir_at(lane: int, d: float) -> Vector2:
	var a := pos_at(lane, d - 0.3)
	var b := pos_at(lane, d + 0.3)
	return (b - a).normalized()

func spawn_pos(lane: int) -> Vector2:
	return (lanes[lane] as PackedVector2Array)[0]

## Closest point on a lane: returns [distance_along, distance_from_road, point]
func project(lane: int, p: Vector2) -> Array:
	var pts: PackedVector2Array = lanes[lane]
	var c: PackedFloat32Array = lane_len[lane]
	var best_d := INF
	var best_s := 0.0
	var best_p := pts[0]
	for i in range(1, pts.size()):
		var a := pts[i - 1]
		var b := pts[i]
		var ab := b - a
		var t := clampf((p - a).dot(ab) / maxf(ab.length_squared(), 0.0001), 0.0, 1.0)
		var q := a + ab * t
		var dd := p.distance_to(q)
		if dd < best_d:
			best_d = dd
			best_s = c[i - 1] + ab.length() * t
			best_p = q
	return [best_s, best_d, best_p]

func dist_to_any_road(p: Vector2) -> float:
	var m := INF
	for k in 4:
		m = minf(m, project(k, p)[1])
	return m

func lane_of_point(p: Vector2) -> int:
	var best := 0
	var bd := INF
	for k in 4:
		var d: float = project(k, p)[1]
		if d < bd:
			bd = d
			best = k
	return best

## A sensible "frontline" stand spot for a hero guarding lane k (35% down the road)
func guard_pos(lane: int) -> Vector2:
	return pos_at(lane, length(lane) * 0.55)

func hero_spawn(slot: int) -> Vector2:
	var p := rot(Vector2(0, -CASTLE_R - 1.6), slot)
	return p
